### ISSUE TITLE
fts search fails when no location specified

### ISSUE THREAD

**Issue by 1tylermitchell** [couchbaselabs/try-cb-python#1]
the combination of "description" and "location" search is fine, but without a location it is not substituting * properly and fails.  Probably routing issue.

**127.0.0.1 - - [19/Apr/2017 08:47:59] "GET /api/hotel/inn/ HTTP/1.1" 404 -**
**127.0.0.1 - - [19/Apr/2017 08:48:04] "GET /api/hotel/hostel/ HTTP/1.1" 404 -**
127.0.0.1 - - [19/Apr/2017 08:48:08] "GET /api/hotel/hostel/seattle/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2017 08:48:10] "GET /api/hotel/hostel/london/ HTTP/1.1" 200 -

**Comment by osfameron** [comment]
Thanks @1tylermitchell, I'm not sure if the original API was originally intended to substitute the * if omitted, but in the recent update for Couchbase server 7.0 we've standardized on the following definition in Swagger: https://docs.couchbase.com/python-sdk/current/hello-world/sample-application.html#/hotels/get_api_hotels__description___location__

> GET /api/hotels/{description}/{location}/

So the location it not optional. The frontend correctly forms this with for example `http://localhost:8080/api/hotels/inn/*/`

I'll close this ticket now, as I believe it's working to spec, but please shout if you have any other comments!
