### ISSUE TITLE
5.0 support will require authentication changes

### ISSUE THREAD

**Issue by 1tylermitchell** [couchbaselabs/try-cb-python#2]
- changes will require library updates (couchbase.py and libcouchbase)
- simple url auth example works

**Comment by shadycuz** [comment]
How do you connect over the encrypted ports using `couchbases://` but still using username and password auth?

**Comment by osfameron** [comment]
Thanks @1tylermitchell. We've recently updated the sample app to support Couchbase Server 7.0 features, I'm closing this old ticket.
