### ISSUE TITLE
Pin to an ubuntu version?

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/try-cb-python#8]
The problem with this is that it will use the *latest* ubuntu version, and couchbase might not be compatible with it:

```
# Set the base image to Ubuntu
FROM ubuntu
```

I would say this should be changed to 

```
FROM ubuntu:16
```

or 

```
FROM ubuntu:14
```

(or latest version that couchbase supports)

**Comment by osfameron** [comment]
Thanks @tleyden ! We've recently updated the app to support Server 7.0 features.
The latest dockerfile has `FROM python:3.9-slim-buster` which specifies both the Python version and the linux version (Debian buster) so this shouldn't be an issue any more.
